sudo: false
python:
- 3.5.3
- 3.6
env:

matrix:
  fast_finish: true
  include:
    - python: 3.5.3
      env: TOXENV=lint
    - python: 3.5.3
      env: TOXENV=pylint
    - python: 3.5.3
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
  allow_failures:
    - python: 3.5.3
      env: TOXENV=pylint

cache:
  directories:
    - $HOME/.cache/pip
install: pip install -U tox
#coveralls
language: python
script: travis_wait 30 tox --develop
#after_success: coveralls